[package]
name = "rust-solution-5"
version = "0.1.0"
authors = ["Sam Herts"]
edition = "2021"

[dependencies]
prime_factorization = "1.0.4"


[profile.release]
codegen-units = 1
lto = true
opt-level = 3


